project:
  type: website
  render:
    - "!LICENSE.md"
    - "!CODE_OF_CONDUCT.md"

website:
  site-url: "https://r-hub.github.io/cransays"
  title: "cransays"
  navbar:
    left:
      - index.qmd

format:
  html:
    toc: true