---
title: "CRAN incoming dashboard"
date: "`r format(Sys.time(), '%F %R UTC%z')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
```

The data in this table stems from our querying ftp://cran.r-project.org/incoming/ We update it every hour.

# Dashboard

```{r get-data}
cran_incoming <- cransays::take_snapshot()
cran_incoming$submitted <- glue::glue("{cran_incoming$howlongago} day(s) ago")
cran_incoming <- dplyr::arrange(cran_incoming,
                                folder,
                                howlongago)
cran_incoming <- dplyr::mutate(cran_incoming,
                               type = ifelse(
  folder %in% c("pretest", "inspect",
                    "recheck",
                     "pending", "publish"),
  folder, "human"
))

library("magrittr")

cran_incoming <- dplyr::select(cran_incoming,
                               package, version, submitted, type, folder) %>%
    dplyr::mutate(folder = as.factor(folder),
                  type = as.factor(type))
```

```{r addmeta}
cran_incoming <- split(cran_incoming, seq_len(nrow(cran_incoming))) %>%
  purrr::map_df(cransays::get_metadata)


```

```{r}
library("magrittr")
DT::datatable(cran_incoming,
              escape = FALSE,
              options = list(pageLength = 500,
                           columnDefs = list(list(type = 'natural', 
                                             targets = 3))),
              filter = "top",
              plugins = "natural") %>% DT::formatStyle(
  'type',
  target = "row",
  backgroundColor = DT::styleEqual(c("pretest", "inspect",
                                 "recheck", "human",
                                 "pending", "publish"), 
                               c("#2165b6", "#e8830c",
                                 "#3cb4b8", "#cf4729",
                                 "#34ba17", "#c04aa9")))

  
```

# Need help with your R package?

Get in touch with us about how we at Locke Data can help you get your package CRAN ready. Fill out [our contact page](//itsalocke.com/#contact).
